site_name: GrOpt

site_url: https://temp.org
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - mkdocs-jupyter
    - search
    - mkdocstrings

nav:
  - Home: index.md
  - Algorithms:
    - OSQP: solvers/osqp_solver.md
  - Python Wrapper:
    - gropt.gropt: python/gropt_py.md
  - C++:
    - Usage: cpp/cpp_info.md
  # - Notebook Test:
  #   - ../examples/diffusion/test.md
