nav:
  - GrOpt: index.md
  - Python:
      - Overview: python/gropt_py.md
      - Problem Init: python/problem.md
      - Constraints: python/constraints.md
      - Solving: python/solvers.md
  - Examples:
      - "examples/"