name: (macOS) Build Python C++ Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-extension:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install numpy matplotlib cython

    - name: Build extension
      run: |
        python setup.py build_ext --inplace

    - name: Test import
      run: |
        python -c "import gropt_dev as gropt; gropt.demo(plot=False);"
